include: package:lints/recommended.yaml

analyzer:
  exclude:
    - '**/.dart_tool/**'
    - '**/build/**'
    - '**/.flutter-plugins/**'
    - '**/.flutter-plugins-dependencies/**'

formatter:
  page_width: 100

linter:
  rules:
    directives_ordering: true
    prefer_single_quotes: true
    sort_pub_dependencies: true
    unawaited_futures: true
