name: aptabase_storage_hive_ce_plus_example
description: Dart example for aptabase_storage_hive_ce_plus.
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

dependencies:
  aptabase_plus:
    path: ../../aptabase_plus
  aptabase_storage_hive_ce_plus:
    path: ..

# This example intentionally has no Flutter dependency.

dev_dependencies:
  lints: ^6.1.0
