name: aptabase_storage_shared_preferences_plus
description: SharedPreferencesAsync storage adapter for queued Aptabase Plus events in Flutter apps.
version: 0.1.0
homepage: https://aptabase.com
repository: https://github.com/aptabase/aptabase_flutter
issue_tracker: https://github.com/aptabase/aptabase_flutter/issues
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.1'

resolution: workspace

dependencies:
  aptabase_plus:
    path: ../aptabase_plus
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  shared_preferences_platform_interface: ^2.4.2
