name: aptabase_plus_example
description: Dart-only example for aptabase_plus.
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

dependencies:
  aptabase_plus:
    path: ..

dev_dependencies:
  lints: ^6.1.0
